name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - master

concurrency: 
  group: ${{ github.ref_name }}
  cancel-in-progress: true

env:
  CI: true
  GIT_AUTHOR_EMAIL: Dzuelu@users.noreply.github.com
  GIT_AUTHOR_NAME: Dzuelu

jobs:
  # TODO fix and then add tests run before deploy
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: Dzuelu/factorio-blueprint-decoder
          ref: master

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: |
          git config --global user.email "$GIT_AUTHOR_EMAIL"
          git config --global user.name "$GIT_AUTHOR_NAME"
        shell: sh

      - run: npm install
        shell: sh

      - run: npm run build
        shell: sh

      - run: npm run deploy
        shell: sh
