name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - master

jobs:
  # TODO fix and then add tests run before deploy
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm run build
        shell: sh

      - run: npm run deploy
        shell: sh
